### PR TITLE
Inspect containerd version and switch config version accordingly

### LINKED ISSUE #143: nvidia-device-plugin-daemonset toolkit validation fails with containerd
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
 
I am trying to use gpu operator in a kubernetes cluster created using `cluster-api` for azure. As I installed the operator, I'm running into an issue where the `nvidia-device-plugin-daemonset` fails to come up, and crashes in init container which tries to run a validation pod. On further inspection, I noticed that it was failing with `ImageInspectError`. The event log:

```
Events:
  Type     Reason         Age                   From               Message
  ----     ------         ----                  ----               -------
  Normal   Scheduled      10m                   default-scheduler  Successfully assigned gpu-operator-resources/nvidia-device-plugin-daemonset-f99md to cl-gpu-md-0-f4gm6
  Warning  InspectFailed  10m (x3 over 10m)     kubelet            Failed to inspect image "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2": rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused"
  Warning  Failed         10m (x3 over 10m)     kubelet            Error: ImageInspectError
  Normal   Pulling        9m57s                 kubelet            Pulling image "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2"
  Normal   Pulled         9m53s                 kubelet            Successfully pulled image "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2"
  Normal   Created        9m8s (x4 over 9m53s)  kubelet            Created container toolkit-validation
  Normal   Started        9m8s (x4 over 9m53s)  kubelet            Started container toolkit-validation
  Normal   Pulled         9m8s (x3 over 9m52s)  kubelet            Container image "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2" already present on machine
  Warning  BackOff        10s (x45 over 9m51s)  kubelet            Back-off restarting failed container
```

PS: I'm using `containerd` for container management

The vm type is azure [ncv3 series](https://docs.microsoft.com/en-us/azure/virtual-machines/ncv3-series)

### 2. Steps to reproduce the issue

1. Create k8s cluster with one worker node with nvidia gpu
2. Once the nodes are ready, install the nvidia gpu operator using `helm install --wait --generate-name nvidia/gpu-operator --set operator.defaultRuntime=containerd`
3. Observe `kubectl -n gpu-operator-resources get pods`

### PR DESCRIPTION
**Pull request by shysank**
This pr inspects containerd version and switches b/w v1 and v2 config spec accordingly. Fixes [#143](https://github.com/NVIDIA/gpu-operator/issues/143)

### CODE REVIEW

**Comment by shysank** [comment]
Lots of vendor files added because I've added containerd as a dependency to query for the version.  We can avoid by using `ctr version` to inspect version. However, this means we have an added dependency on `ctr` to be present in the node, and the tests were failing too.   Happy to switch it to `ctr version` if we're okay with it. wdyt?

/cc @klueska

**Comment by shysank** [comment]
Logs from testing:

```
time="2021-02-17T17:34:38Z" level=info msg="Setting up runtime"
time="2021-02-17T17:34:38Z" level=info msg="Starting 'setup' for containerd"
time="2021-02-17T17:34:38Z" level=info msg="Parsing arguments: [/usr/local/nvidia/toolkit]"
time="2021-02-17T17:34:38Z" level=info msg="Successfully parsed arguments"
time="2021-02-17T17:34:38Z" level=info msg="Loading config: //run/docker/containerd/containerd.toml"
time="2021-02-17T17:34:38Z" level=info msg="Successfully loaded config"
time="2021-02-17T17:34:38Z" level=info msg="version not present in config"
time="2021-02-17T17:34:38Z" level=info msg="containerd version is v1.3.9"
time="2021-02-17T17:34:38Z" level=info msg="Updating config"
time="2021-02-17T17:34:38Z" level=info msg="Updating V2 config"
time="2021-02-17T17:34:38Z" level=info msg="Successfully updated config"
time="2021-02-17T17:34:38Z" level=info msg="Flushing config"
time="2021-02-17T17:34:38Z" level=info msg="Successfully flushed config"
time="2021-02-17T17:34:38Z" level=info msg="Sending SIGHUP signal to containerd"
time="2021-02-17T17:34:38Z" level=info msg="Successfully signaled containerd"
time="2021-02-17T17:34:38Z" level=info msg="Completed 'setup' for containerd"
time="2021-02-17T17:34:38Z" level=info msg="Shutting Down"
time="2021-02-17T17:34:38Z" level=info msg="Completed nvidia-toolkit"
```

**Comment by klueska** [comment]
As the comment above suggests, we do development on gitlab, not github. Please open an MR there.

**Comment by shysank** [comment]
closing this in favor of https://gitlab.com/nvidia/container-toolkit/container-config/-/merge_requests/63

**Pull request closed without merging**
